# @codegen-command: just codegen-kube-vip
# @generated
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v1.0.0
  name: kube-vip-svc-ds
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-svc-ds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-vip-svc-ds
        app.kubernetes.io/version: v1.0.0
    spec:
      containers:
        - args:
            - manager
          env:
            - name: cp_namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: svc_election
              value: "true"
            - name: svc_enable
              value: "true"
            - name: svc_leasename
              value: plndr-svcs-lock
            - name: vip_arp
              value: "true"
            - name: vip_nodename
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: ghcr.io/kube-vip/kube-vip
          imagePullPolicy: IfNotPresent
          name: kube-vip
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
              drop:
                - ALL
      hostNetwork: true
      priorityClassName: critical-application-infra
      serviceAccountName: kube-vip
