- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present
  when: ansible_facts['os_family'] == 'Debian'
- name: Set up zsh config
  ansible.builtin.template:
    src: zshrc
    dest: "{{ zsh__config_path }}/.zshrc"
    mode: u+rw-x,o-rwx,g-rwx
    owner: "{{ zsh__config_owner }}"
    group: "{{ zsh__config_group }}"
- name: Set up zsh environment
  ansible.builtin.template:
    src: zshenv
    dest: "{{ zsh__config_path }}/.zshenv"
    mode: u+rw-x,o-rwx,g-rwx
    owner: "{{ zsh__config_owner }}"
    group: "{{ zsh__config_group }}"
