ARG USERNAME=vscode
ARG USERID=1000
ARG GROUPID=1000

FROM scratch AS ctx
COPY build_files /

FROM quay.io/fedora/fedora-minimal:44

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh

WORKDIR /home/${USERNAME}
USER ${USERNAME}
