VERSION 0.8
FROM alpine

# Builds our base image that can be used standalone as well as for the Kairos Factory:
# https://kairos.io/docs/reference/kairos-factory/
base-image:
    ARG TAG=dev
    ARG TARGETPLATFORM
    FROM DOCKERFILE \
      -f Dockerfile \
      --platform $TARGETPLATFORM \
      .
    SAVE IMAGE --push ghcr.io/marinatedconcrete/ubuntu-24-lts:$TAG

kairos-image:
    ARG --required TAG

    ARG KAIROS_ORG=kairos-io
    # renovate: datasource=github-releases depName=kairos-io/kairos
    ARG KAIROS_VERSION=v3.1.1

    FROM github.com/$KAIROS_ORG/kairos:$KAIROS_VERSION+base-image \
        --BASE_IMAGE=ghcr.io/marinatedconcrete/ubuntu-24-lts:$TAG \
        --BOOTLOADER=grub \
        --FAMILY=ubuntu \
        --FLAVOR=ubuntu \
        --FLAVOR_RELEASE=24.04 \
        --MODEL=generic \
        --VARIANT=standard
    SAVE IMAGE --push ghcr.io/marinatedconcrete/kairos-ubuntu-24-lts:$TAG
