VERSION 0.7
# renovate: datasource=docker depName=python versioning=docker
ARG PYTHON_VERSION=3.12.6-bookworm
FROM python:$PYTHON_VERSION

image:
    COPY requirements.txt .
    RUN pip install -r requirements.txt
    # Firmware appears to be unversioned in a way that renovate can handle
    ARG FIRMWARE_BRANCH='main'
    RUN git clone https://github.com/NabuCasa/silabs-firmware.git --branch $FIRMWARE_BRANCH
    ARG TAG='latest'
    SAVE IMAGE --push ghcr.io/marinatedconcrete/universal-silabs-flasher:$TAG


