VERSION 0.7
FROM alpine

# renovate: datasource=github-releases depName=k3s-io/k3s versioning=docker
ARG --global K3S_VERSION=v1.27.9+k3s1
# renovate: datasource=github-releases depName=kairos-io/kairos
ARG --global KAIROS_VERSION=v3.0.14

image:
    BUILD +image-amd64
    # Not sure why this isn't working
    # ./i/kairos-ubuntu-22-lts+image-generic | WARN images/kairos-ubuntu-22-lts/Earthfile line 55:4: The command 'RUN apt-get update' failed: failed to read expected number of bytes: unexpected EOF
    # Error: unlazy force execution: failed to compute cache key: failed to read expected number of bytes: unexpected EOF
    #BUILD +image-arm64

image-amd64:
    BUILD +image-generic \
        --PLATFORM=amd64 \
        --DEVICE=generic \
        --UBUNTU_VERSION=22.04

image-arm64:
    BUILD +image-generic \
        --PLATFORM=arm64 \
        --DEVICE=rpi4 \
        --UBUNTU_VERSION=22.04

push:
    ARG TAG
    BUILD +push-amd64 --TAG=$TAG
    # Disabled due to build not working
    #BUILD +push-arm64

push-amd64:
    ARG TAG
    BUILD +push-generic \
        --PLATFORM=amd64 \
        --DEVICE=generic \
        --UBUNTU_VERSION=22.04 \
        --TAG=$TAG

push-arm64:
    ARG TAG
    BUILD +push-generic \
        --PLATFORM=arm64 \
        --DEVICE=rpi4 \
        --UBUNTU_VERSION=22.04 \
        --TAG=$TAG

image-generic:
    ARG PLATFORM
    ARG DEVICE
    ARG UBUNTU_VERSION
    ARG REPOSITORY=quay.io/kairos/ubuntu
    ARG FLAVOR=standard
    # Final image looks something like this:
    # quay.io/kairos/ubuntu:22.04-standard-amd64-generic-v2.5.0-k3sv1.27.9-k3s1
    ARG k3s_tag=$(echo "$K3S_VERSION" | tr '+' '-')
    FROM --platform=linux/$PLATFORM $REPOSITORY:$UBUNTU_VERSION-$FLAVOR-$PLATFORM-$DEVICE-$KAIROS_VERSION-k3s$k3s_tag

    # Get Package Manager Updates
    RUN apt-get update

    # Install Additional Packages
    RUN apt-get install -y --no-install-recommends \
        htop \
        usbutils \
        vim \
        zsh

    # Cleanup
    RUN apt-get clean && rm -rf /var/lib/apt/lists/*

push-generic:
    ARG PLATFORM
    ARG DEVICE
    ARG UBUNTU_VERSION
    ARG TAG
    FROM +image-generic --PLATFORM=$PLATFORM --DEVICE=$DEVICE --UBUNTU_VERSION=$UBUNTU_VERSION
    RUN echo "MARINATEDCONCRETE_IMAGE=ghcr.io/marinatedconcrete/kairos-ubuntu-22-lts:$TAG" >> /etc/os-release
    SAVE IMAGE --push ghcr.io/marinatedconcrete/kairos-ubuntu-22-lts:$TAG
