---
apiVersion: v1
kind: Service
metadata:
  name: factorio-admin-svc
spec:
  selector:
    app.kubernetes.io/name: factorio
  ports:
    - name: web
      protocol: TCP
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: factorio-game-svc
spec:
  selector:
    app.kubernetes.io/name: factorio
  ports:
    - name: game
      protocol: UDP
      port: 34197
