---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: una-mongodb-scripts-configmap
    files:
      - configmap/generate-init-mongo.sh
      - configmap/shutdown-mongo.js
images:
  - name: busybox
    newTag: 1.37.0@sha256:e226d6308690dbe282443c8c7e57365c96b5228f0fe7f40731b5d84d37a06839
  - name: lscr.io/linuxserver/unifi-network-application
    newTag: 10.0.162@sha256:7948b8c2ca4cd9bf9e1839f3e399c320e0a8318cd54dc807c247f48702f4b157
  - name: mongo
    newTag: 8.0.18@sha256:ea2d3389d685f1cbd41cbad8c9d0fb1a7448ede26263cde4e5e61aa9050d7783
resources:
  - statefulset.yml
  - serverstransport.yml
  - service.yml
