---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: una-mongodb-scripts-configmap
    files:
      - configmap/generate-init-mongo.sh
      - configmap/shutdown-mongo.js
images:
  - name: busybox
    newTag: 1.37.0@sha256:f85340bf132ae937d2c2a763b8335c9bab35d6e8293f70f606b9c6178d84f42b
  - name: lscr.io/linuxserver/unifi-network-application
    newTag: 9.1.120@sha256:dd5ef5b600d0c18e9e928fe88258e3857f94e2e9187f39d6d0e02c5d31182935
  - name: mongo
    newTag: 8.0.9@sha256:3e8fd506d185ea100867c9da5f90414cee744d1545449038c60190f3fd3cc274
resources:
  - statefulset.yml
  - serverstransport.yml
  - service.yml
