---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: una-mongodb-scripts-configmap
    files:
      - configmap/generate-init-mongo.sh
      - configmap/shutdown-mongo.js
images:
  - name: busybox
    newTag: 1.37.0@sha256:2383baad1860bbe9d8a7a843775048fd07d8afe292b94bd876df64a69aae7cb1
  - name: lscr.io/linuxserver/unifi-network-application
    newTag: 10.0.162@sha256:268340299e6a8a85c29800923e242c60ed7baa24557943f0ff5ec4ea52804232
  - name: mongo
    newTag: 8.0.17@sha256:9814652e33f0cf8b9fddea8b46dfc9d8e19b130dcfdd7b510ca58bb0d40c8b71
resources:
  - statefulset.yml
  - serverstransport.yml
  - service.yml
