# See https://kairos.io/docs/reference/kairos-factory/ for more information.

FROM quay.io/kairos/kairos-init:v0.17.3@sha256:7f35a5025559ac2f1f5f52e89e52a91f67b783ef03ff1c1ac06a690a482e805d AS kairos-init

# Make build scripts available without copies in the final image.
FROM scratch AS ctx
COPY build_files /

FROM fedora:45
LABEL org.opencontainers.image.title="A custom Fedora-based Kairos image."
LABEL org.opencontainers.image.title="kairos-fedora"
ARG MODEL=generic
ARG TRUSTED_BOOT=false
ARG KUBERNETES_DISTRO=k3s
# renovate: datasource=github-releases depName=k3s-io/k3s
ARG KUBERNETES_VERSION=v1.36.2+k3s1
ARG VERSION

COPY --from=kairos-init /kairos-init /kairos-init

# Install Kairos into the image.
# hadolint ignore=DL3059
RUN /kairos-init \
    -l debug \
    -m "${MODEL}" \
    -s install \
    -t "${TRUSTED_BOOT}" \
    --provider "${KUBERNETES_DISTRO}" \
    --provider-k3s-version "${KUBERNETES_VERSION}" \
    --version "${VERSION}"

# Apply the custom configuration.
# hadolint ignore=DL3059
RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/customization.sh

# Initialize the image.
# hadolint ignore=DL3059
RUN /kairos-init \
    -l debug \
    -m "${MODEL}" \
    -s init \
    -t "${TRUSTED_BOOT}" \
    --provider "${KUBERNETES_DISTRO}" \
    --provider-k3s-version "${KUBERNETES_VERSION}" \
    --version "${VERSION}"

# Apply the final configuration after Kairos initialization.
RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/configure.sh

# Validate the image.
# hadolint ignore=DL3059
RUN /kairos-init \
    validate \
    -t "${TRUSTED_BOOT}"

# hadolint ignore=DL3059
RUN rm /kairos-init
