---
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --device
- op: add
  path: /spec/template/spec/containers/0/args/-
  # The initial vendor and product IDs are 1a64:089a.
  # After the first inference, these IDs change to 18d1:9302.
  # See https://github.com/google-coral/edgetpu/issues/536#issuecomment-1033056048
  value: |
    name: coraltpu
    groups:
      - usb:
          - product: 089a
            vendor: 1a6e
      - usb:
          - product: 9302
            vendor: 18d1
