FROM scratch AS ctx
COPY build_files /

FROM quay.io/buildah/stable:v1.43.2@sha256:e3fa488daa6ca27bfbf5a6b3995b4e7e48b2a3b6ec578391980edbcd59b125a2

LABEL org.opencontainers.image.title="buildah-action-runner"
LABEL org.opencontainers.image.description="Tools needed for a minimal buildah environment in CI."

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/lib/dnf \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh
