FROM scratch AS ctx
COPY build_files /

FROM quay.io/buildah/stable:v1.43.2@sha256:8eca9c2b0adc0ac729980c68d84a2449e2199e303091a60957c11b792ddd49bf

LABEL org.opencontainers.image.title="buildah-action-runner"
LABEL org.opencontainers.image.description="Tools needed for a minimal buildah environment in CI."

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/lib/dnf \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh
