FROM scratch AS ctx
COPY build_files /

FROM quay.io/buildah/stable:v1.43.2@sha256:836f1db7d8a21dc26d63f6c4ef930cde3f2a69f3e9f4cae9cc6751ec7b7a40dc

LABEL org.opencontainers.image.title="buildah-action-runner"
LABEL org.opencontainers.image.description="Tools needed for a minimal buildah environment in CI."

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/lib/dnf \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh
