# Write logs to the container stdout with a timestamp.
log_dest stdout
log_timestamp_format %Y-%m-%dT%H:%M:%S

# Use separate authentication for each listener. The liveness probe uses a separate listener.
per_listener_settings true

# Use this listener only for the liveness probe.
listener 0 /mosquitto/socket
allow_anonymous true

# Configure the default listener.
listener 1883

password_file /mosquitto/data/password.conf

include_dir /mosquitto/config.d/
