---
# tasks file for minikube_test
- name: Start minikube
  ansible.builtin.command:
    argv:
      - minikube
      - start
      - --interactive=false
      - "--profile={{ kubernetes_core_k8s__context | default(minikube_test__test_name) }}"
      - "--kubernetes-version={{ minikube_test__kubernetes_version }}"
      - --force
  changed_when: true
  notify: stop minikube
- name: Apply kustomization
  kubernetes.core.k8s:
    apply: true
    context: "{{ kubernetes_core_k8s__context | default(minikube_test__test_name) }}"
    definition: "{{ lookup('kubernetes.core.kustomize', dir=minikube_test__test_dir) }}"
