apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/paperless-ngx/paperless-ngx
    newTag: 3.1.0@sha256:49eba766581b9134cfa6b584b9eb718355fb9cfbd44b2a7c9c72a427d4891648
  - name: ghcr.io/servercontainers/samba:smbd-only-latest
    digest: sha256:cf0d36de0477093e5cb6fd19b98d7a911a523c0976c20e634bd42c2bcffe172c
resources:
  - pvc.yml
  - statefulset.yml
  - service.yml
  - samba-deployment.yml
  - samba-service.yml
