apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/paperless-ngx/paperless-ngx
    newTag: 2.16.2@sha256:2096725a544b81d07d35ac123aca079bcb859e03c73d03acb0105dd2629b3dea
resources:
  - pvc.yml
  - statefulset.yml
  - service.yml
