apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/paperless-ngx/paperless-ngx
    newTag: 3.1.3@sha256:aa810a36942c63d4ee70d00eda7236cd3d6acfb7eb3f7987fb568ed14df8817a
  - name: ghcr.io/servercontainers/samba:smbd-only-latest
    digest: sha256:cf0d36de0477093e5cb6fd19b98d7a911a523c0976c20e634bd42c2bcffe172c
resources:
  - pvc.yml
  - statefulset.yml
  - service.yml
  - samba-deployment.yml
  - samba-service.yml
