# Store new scans in this volume.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-scans
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-encrypted
  resources:
    requests:
      storage: 1Gi
---
# Store the Paperless database in this volume.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-encrypted
  resources:
    requests:
      storage: 4Gi
---
# Store processed Paperless documents in this volume.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-encrypted
  resources:
    requests:
      storage: 1Gi
---
# This volume is for document exports. See https://docs.paperless-ngx.com/administration/#utilities-exporter
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-export
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-encrypted
  resources:
    requests:
      storage: 100Mi
