apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - deployment.yml
  - service.yml

images:
  - name: ghcr.io/servercontainers/samba:smbd-only-latest
    digest: sha256:50d28991ed82de9e629534293ca38e9aaacf6757bc79b4fe14f5ace0041ac78e
