apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - deployment.yml
  - service.yml

images:
  - name: ghcr.io/servercontainers/samba:smbd-only-latest
    digest: sha256:41e6de7c5125765e63f924a4b7c82041a1913bf223b12f86bdeb26533123bf09
