apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - deployment.yml
  - service.yml

images:
  - name: ghcr.io/servercontainers/samba:smbd-only-latest
    digest: sha256:3141630a27e18c8cd90e3330470bca380094cfeda22a904f0a20fc59db8dcafd
