apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - deployment.yml
  - service.yml

images:
  - name: ghcr.io/servercontainers/samba:smbd-only-latest
    digest: sha256:18a79ec2dcebf5da4f5197a9dc67a71a29a0545d115544c49ffaf1971b07e104
