apiVersion: v1
kind: Service
metadata:
  name: samba
spec:
  selector:
    app.kubernetes.io/name: samba
  ports:
    - protocol: TCP
      port: 445
  type: LoadBalancer
  loadBalancerClass: kube-vip.io/kube-vip-class
