---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/kube-vip/kube-vip
    newTag: v1.2.2@sha256:b2e00d870995f9c32f4e87d28a4ddf10d53bf54b50dc4456c3ea8bb94a52b414
resources:
  - rbac.yml
  - daemonset/services.yml
  - daemonset/vip.yml
