---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/kube-vip/kube-vip
    newTag: v1.2.1@sha256:49b77655f9f109bedc5eb25723bb0e4c57d8513ba33cc69c31be3f243eb2386d
resources:
  - rbac.yml
  - daemonset/services.yml
  - daemonset/vip.yml
