apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - pvc.yml
  - deployment.yml
  - service.yml

images:
  - name: redis
    newTag: 8.8.1@sha256:8c98991a43d08fe38f347128385c3abd68aa4d8c04f17a2809a579adef1b59b8
