apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - pvc.yml
  - deployment.yml
  - service.yml

images:
  - name: redis
    newTag: 8.4.0@sha256:73dad4271642c5966db88db7a7585fae7cf10b685d1e48006f31e0294c29fdd7
