apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - pvc.yml
  - deployment.yml
  - service.yml

images:
  - name: redis
    newTag: 8.6.1@sha256:315270d166080f537bbdf1b489b603aaaa213cb55a544acfa51feb7481abb1c0
