---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: mosquitto-default-config-configmap
    files:
      - configmap/default-config/mosquitto.conf
  - name: mosquitto-scripts-configmap
    files:
      - configmap/scripts/create_password.conf.sh
images:
  - name: eclipse-mosquitto
    newTag: 2.0.22@sha256:75042dd2dd262dff9eb29c47da26d8ee57211a7bc6fc51bae55badc5fc9f6724
resources:
  - persistentvolumeclaim.yml
  - deployment.yml
  - service.yml
