VERSION 0.7
# renovate: datasource=docker depName=python
ARG PYTHON_TAG=3.12-alpine
FROM python:$PYTHON_TAG

WORKDIR /ansible

ansible:
  # renovate: datasource=pip depName=ansible
  ARG ANSIBLE_VERSION=8.4.0
  RUN pip install ansible==$ANSIBLE_VERSION

ansible-with-roles:
  FROM +ansible
  COPY . .

ansible-playbook:
  ARG playbook=playbook.yml
  ARG hosts=localhost
  ARG roles
  ARG vars
  RUN echo "- hosts:" > $playbook
  FOR host IN $hosts
    RUN echo "  - $host" >> $playbook
  END
  RUN echo "  roles:" >> $playbook
  FOR role IN $roles
    RUN echo "  - $role" >> $playbook
  END
  RUN echo "  vars:" >> $playbook
  FOR --sep '|' var IN $vars
    RUN echo "    $var" >> $playbook
  END
  SAVE ARTIFACT $playbook
  RUN cat $playbook

zsh:
  FROM +ansible-with-roles
  RUN mkdir /configs
  COPY (+ansible-playbook/playbook.yml --roles=zsh --vars="zsh__config_path: /configs|zsh__config_owner: root|zsh__config_group: root") .
  RUN ansible-playbook playbook.yml
  SAVE ARTIFACT /configs
