VERSION 0.7
FROM alpine 

image:
  ARG EARTHLY_GIT_BRANCH
  ARG TAG=$EARTHLY_GIT_BRANCH

  COPY ./run.sh /
  # Use Ansible to generate the zsh configs
  COPY ../../ansible+zsh/configs /assets
  SAVE IMAGE --push ghcr.io/marinatedconcrete/kairos-zsh-bundle:$TAG
