---
name: Run checks
on:
  push:

env:
  DEVCONTAINER_BASE_TAG: candidate-${{ github.sha }}

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Docker
        uses: docker/setup-docker-action@77e84dbf09b47d1e29270283c22f16145aa85ca1 # v5
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Candidate Base Image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: images/devcontainer-base
          file: images/devcontainer-base/Containerfile
          load: true
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/devcontainer-base:${{ env.DEVCONTAINER_BASE_TAG }}
      - name: Build devcontainer image
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          cacheFrom: ghcr.io/marinatedconcrete/config-devcontainer
          cacheTo: ghcr.io/marinatedconcrete/config-devcontainer
          env: |
            CI=1
          imageName: ghcr.io/marinatedconcrete/config-devcontainer
          push: filter
          refFilterForPush: refs/heads/main
  check-format:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build Candidate Base Image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: images/devcontainer-base
          file: images/devcontainer-base/Containerfile
          load: true
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/devcontainer-base:${{ env.DEVCONTAINER_BASE_TAG }}
      - name: Check formatting
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          cacheFrom: ghcr.io/marinatedconcrete/config-devcontainer
          env: |
            CI=1
          imageName: ghcr.io/marinatedconcrete/config-devcontainer
          push: never
          runCmd: just check-format
  kustomization-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build Candidate Base Image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: images/devcontainer-base
          file: images/devcontainer-base/Containerfile
          load: true
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/devcontainer-base:${{ env.DEVCONTAINER_BASE_TAG }}
      - name: Validate configs
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          cacheFrom: ghcr.io/marinatedconcrete/config-devcontainer
          env: |
            CI=1
          imageName: ghcr.io/marinatedconcrete/config-devcontainer
          push: never
          runCmd: just kustomization-test ${{ matrix.kustomization-test }}
    strategy:
      matrix:
        kustomization-test:
          - factorio
          - kube-vip
          - mosquitto
          - paperless
          - priorityclass
          - unifi-network-application
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build Candidate Base Image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: images/devcontainer-base
          file: images/devcontainer-base/Containerfile
          load: true
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/devcontainer-base:${{ env.DEVCONTAINER_BASE_TAG }}
      - name: Validate configs
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          cacheFrom: ghcr.io/marinatedconcrete/config-devcontainer
          env: |
            CI=1
          imageName: ghcr.io/marinatedconcrete/config-devcontainer
          push: never
          runCmd: just lint
