---
name: Build Kairos ZSH Bundle

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/kairos-zsh-bundle.yml
      - ansible/roles/zsh/**
      - images/kairos-zsh-bundle/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/kairos-zsh-bundle.yml
      - ansible/roles/zsh/**
      - images/kairos-zsh-bundle/**

jobs:
  build-container:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      packages: "write"

    steps:
      - uses: earthly/actions-setup@v1.0.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # renovate: datasource=docker depName=earthly/earthly
          version: "v0.7.20"
      - uses: "actions/checkout@v4"

      - name: "Login to GitHub Container Hub"
        run: docker login --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" ghcr.io

      - id: tags
        run: echo "name=$BRANCH" | tr / - >> "$TAG_ENV"
        env:
          BRANCH: ${{ github.event_name != 'pull_request' && 'latest' || format('pr-{0}', github.head_ref) }}

      - name: "Build Kairos ZSH Bundle"
        run: earthly ./images/kairos-zsh-bundle/+image --TAG=$TAG
        env:
          TAG: ${{ steps.tags.outputs.name }}
          EARTHLY_CI: true
          EARTHLY_PUSH: true
          # Only one platform per https://docs.earthly.dev/docs/earthly-command#build-options
          EARTHLY_PLATFORMS: linux/amd64
