---
name: Build Kairos Ubuntu 22 LTS

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/kairos-ubuntu-22-lts.yml
      - images/kairos-ubuntu-22-lts/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/kairos-ubuntu-22-lts.yml
      - images/kairos-ubuntu-22-lts/**

jobs:
  build-container:
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      EARTHLY_ORG: marinatedconcrete
      EARTHLY_SATELLITE: config-repo
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: earthly/actions-setup@v1.0.13
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # renovate: datasource=docker depName=earthly/earthly
          version: "v0.8.7"
      - uses: actions/checkout@v4.1.4
      - uses: docker/setup-qemu-action@v3

      - name: Login to GitHub Container Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        env:
          EARTHLY_CI: true
        run: earthly ./images/kairos-ubuntu-22-lts/+image

      - name: Push Image
        env:
          EARTHLY_CI: true
          EARTHLY_PUSH: ${{ github.event_name != 'pull_request' }}
        run: earthly ./images/kairos-ubuntu-22-lts/+push
