name: "Publish dev container features"
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/validate-devcontainer-feature.yml
      - devcontainer/features/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/validate-devcontainer-feature.yml
      - devcontainer/features/**
  release:
    types:
      - created

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: "Publish Features"
        uses: devcontainers/action@v1.4.2
        with:
          publish-features: "true"
          base-path-to-features: "./devcontainer/features/src"
          generate-docs: "false"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
