---
name: Build Universal Silabs Flasher

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/universal-silabs-flasher.yml
      - images/universal-silabs-flasher/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/universal-silabs-flasher.yml
      - images/universal-silabs-flasher/**

jobs:
  build-container:
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      EARTHLY_ORG: marinatedconcrete
      EARTHLY_SATELLITE: config-repo
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      packages: "write"

    steps:
      - uses: earthly/actions-setup@v1.0.13
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # renovate: datasource=docker depName=earthly/earthly
          version: "v0.8.9"
      - uses: "actions/checkout@v4.1.4"

      - name: "Login to GitHub Container Hub"
        run: docker login --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" ghcr.io

      - id: tags
        run: echo "TAG=$BRANCH" | tr / _ >> "$GITHUB_ENV"
        env:
          BRANCH: ${{ github.event_name != 'pull_request' && 'latest' || format('pr-{0}', github.head_ref) }}

      - name: "Build Universal Silabs Flasher"
        run: earthly ./images/universal-silabs-flasher/+image --TAG=$TAG
        env:
          EARTHLY_CI: true
          EARTHLY_PUSH: true
          # Only one platform per https://docs.earthly.dev/docs/earthly-command#build-options
          EARTHLY_PLATFORMS: linux/amd64
