---
name: Build USB Sidecar

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/usb-image.yml
      - images/usb-image/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/usb-image.yml
      - images/usb-image/**

jobs:
  build-container:
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      EARTHLY_ORG: marinatedconcrete
      EARTHLY_SATELLITE: config-repo
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      packages: "write"

    steps:
      - uses: earthly/actions-setup@v1.0.12
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # renovate: datasource=docker depName=earthly/earthly
          version: "v0.8.6"
      - uses: "actions/checkout@v4.1.1"

      - name: "Login to GitHub Container Hub"
        if: github.event_name != 'pull_request'
        run: docker login --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" ghcr.io

      - name: "Build USB Container Image"
        run: earthly ./images/usb-image/+image
        env:
          EARTHLY_CI: true
          EARTHLY_PUSH: ${{ github.event_name != 'pull_request' }}
          # Only one platform per https://docs.earthly.dev/docs/earthly-command#build-options
          EARTHLY_PLATFORMS: linux/amd64
