---
name: Validate configurations
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      EARTHLY_ORG: marinatedconcrete
      EARTHLY_SATELLITE: config-repo
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1.0.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # renovate: datasource=docker depName=earthly/earthly
          version: "0.8.4"
      - uses: actions/checkout@v4.1.1
      - name: Run validation checks
        run: |
          earthly +validate
        env:
          EARTHLY_CI: true
  lint:
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      EARTHLY_ORG: marinatedconcrete
      EARTHLY_SATELLITE: config-repo
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1.0.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # renovate: datasource=docker depName=earthly/earthly
          version: "0.8.4"
      - uses: actions/checkout@v4.1.1
      - name: Run lint checks
        run: |
          earthly +lint
        env:
          EARTHLY_CI: true
