name: "Validate devcontainer-feature.json files"
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/validate-devcontainer-feature.yml
      - devcontainer/features/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/validate-devcontainer-feature.yml
      - devcontainer/features/**

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Validate devcontainer-feature.json files"
        uses: devcontainers/action@v1.4.2
        with:
          validate-only: "true"
          base-path-to-features: "./devcontainer/features/src"
