---
name: Validate configurations
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "0.7.1"
      - uses: actions/checkout@v4
      - name: Run validation checks
        run: |
          earthly +validate
        env:
          EARTHLY_CI: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "0.7.1"
      - uses: actions/checkout@v4
      - name: Run lint checks
        run: |
          earthly +lint
        env:
          EARTHLY_CI: true
